POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC50ZXN0IiwiZXhwIjoxNzA2NDgwMTg4LCJ1c2VySWQiOjF9.bsLkrPCsAaP8uldbCsn5144l8se8ya3KqnQrpWIasvk

{
    "name": "Test event",
    "description": "A test event",
    "location": "A test location",
    "dateTime": "2025-01-01T15:30:00.000Z"
}
